#!/usr/bin/env python3
"""Autogenerated control-chain trace from a ULog.

Prints the whole path from gyro to motors as a tree: what each module takes in,
what it puts out, at what rate, and what triggered it. Aggregates - rates,
magnitudes and trigger sources - never individual messages.

    python3 trace_chain.py flight.ulg
    python3 trace_chain.py flight.ulg --values      # add signal magnitudes
    python3 trace_chain.py flight.ulg --mode Attitude   # restrict to one control level

THE RATE CAVEAT, which this tool exists to get right
----------------------------------------------------
The logger downsamples most of these topics (logged_topics.cpp), so counting
samples in a ULog measures the LOGGER, not the software. vehicle_angular_velocity
is capped at 20 ms - count its samples and a 250 Hz inner loop looks like 50 Hz.
actuator_motors is capped at 100 ms and looks like 10 Hz.

So every rate below is labelled:
  measured   the module's own loop dt, from mc_controller_status - a real rate
  capped     logger-limited; the true rate is >= this, shown with the cap
  on-change  published only when the value changes; the rate is meaningful as-is

For true publication rates of capped topics, use the running system instead:
    uorb top -1          # live publication rates
    work_queue status    # which queue runs what, and how often
    perf                 # per-module cycle time  (hardware only - reads 0us in SITL)
"""
import argparse
import sys

import numpy as np
from pyulog import ULog

# Logger downsample caps, milliseconds, from src/modules/logger/logged_topics.cpp.
# 0 means uncapped (logged at full publication rate).
LOG_CAP_MS = {
    "vehicle_angular_velocity": 20, "vehicle_attitude": 50,
    "vehicle_attitude_setpoint": 50, "vehicle_rates_setpoint": 20,
    "vehicle_torque_setpoint": 20, "vehicle_thrust_setpoint": 20,
    "vehicle_local_position": 100, "vehicle_local_position_setpoint": 100,
    "actuator_motors": 100, "mc_controller_status": 20,
    "trajectory_setpoint": 200, "manual_control_setpoint": 200,
    "hover_thrust_estimate": 100, "takeoff_status": 1000,
    "vehicle_control_mode": 0, "vehicle_status": 0, "vehicle_land_detected": 0,
    "vehicle_constraints": 0, "control_allocator_status": 0,
    "rate_ctrl_status": 0, "actuator_controls_status_0": 0,
}

# The chain. Each stage: (label, trigger topic, queue, inputs, outputs, note).
# Edited by hand when the architecture changes - it is the *claimed* structure, and
# the point of the tool is to check the claim against what the log actually shows.
CHAIN = [
    ("sensors / IMU pipeline", "sensor_accel / sensor_gyro", "wq:SPIx / INS",
     ["sensor_gyro", "sensor_accel"],
     ["vehicle_angular_velocity", "vehicle_acceleration"],
     "gyro filtering + downsample to IMU_GYRO_RATEMAX"),

    ("ekf2", "sensor topics", "wq:INS",
     ["vehicle_angular_velocity", "sensor_combined", "vehicle_gps_position"],
     ["vehicle_attitude", "vehicle_local_position"],
     "state estimation"),

    ("commander", "internal 100 Hz", "task",
     ["vehicle_status_flags", "manual_control_setpoint"],
     ["vehicle_control_mode", "vehicle_status"],
     "resolves the flight mode -> the flags the framework maps to a ControlLevel"),

    ("flight_mode_manager", "vehicle_local_position", "wq:nav_and_controllers",
     ["vehicle_local_position", "manual_control_setpoint", "vehicle_control_mode"],
     ["trajectory_setpoint", "vehicle_constraints"],
     "UNCHANGED by the framework - still the setpoint generator"),

    ("mc_controller_outer  [OuterLoop]", "vehicle_local_position", "wq:nav_and_controllers",
     ["vehicle_local_position", "vehicle_attitude", "trajectory_setpoint",
      "vehicle_constraints", "hover_thrust_estimate", "vehicle_control_mode"],
     ["vehicle_attitude_setpoint", "vehicle_local_position_setpoint", "takeoff_status"],
     "only when the controller sets hasOuterStage(); publishes at Trajectory level only"),

    ("mc_controller  [inner]", "vehicle_angular_velocity", "wq:rate_ctrl",
     ["vehicle_angular_velocity", "vehicle_attitude", "vehicle_attitude_setpoint",
      "manual_control_setpoint", "vehicle_control_mode", "hover_thrust_estimate",
      "control_allocator_status"],
     ["vehicle_torque_setpoint", "vehicle_thrust_setpoint", "vehicle_rates_setpoint",
      "mc_controller_status", "rate_ctrl_status", "actuator_controls_status_0"],
     "state -> command -> YOUR update() -> output stage"),

    ("control_allocator", "vehicle_torque_setpoint", "wq:rate_ctrl",
     ["vehicle_torque_setpoint", "vehicle_thrust_setpoint"],
     ["actuator_motors", "control_allocator_status"],
     ""),

    ("MixingOutput -> ESCs", "actuator_motors", "driver",
     ["actuator_motors"], [],
     "kill_switch_2 rotor-failure injection lives here, downstream of allocation"),
]

# Control-level segmentation by nav_state.
LEVELS = {"Trajectory": {2, 3, 4, 5, 10, 14, 17, 20, 21, 22},
          "Attitude": {15}, "BodyRate": {16}}
AIR_M = 4.0


class Log:
    def __init__(self, path):
        self.u = ULog(path)
        self.topics = {x.name: x.data for x in self.u.data_list}
        self.t0, self.t1 = self._air_window()

    def _air_window(self):
        lp = self.topics.get("vehicle_local_position")
        if lp is None:
            return None, None
        t = np.asarray(lp["timestamp"], dtype=float) / 1e6
        z = np.asarray(lp["z"], dtype=float)
        i = np.where((-z) >= AIR_M)[0]
        return (t[i[0]], t[i[-1]]) if len(i) else (t[0], t[-1])

    def restrict(self, level):
        """Limit the window to segments of one control level."""
        vs = self.topics.get("vehicle_status")
        if vs is None or level is None:
            return None
        tv = np.asarray(vs["timestamp"], dtype=float) / 1e6
        nv = np.asarray(vs["nav_state"], dtype=float).astype(int)
        want, spans, i = LEVELS[level], [], 0
        while i < len(nv):
            j = i
            while j + 1 < len(nv) and nv[j + 1] == nv[i]:
                j += 1
            if nv[i] in want:
                spans.append((tv[i], tv[j]))
            i = j + 1
        return spans

    def mask(self, name, spans):
        d = self.topics.get(name)
        if d is None:
            return None, None
        ts = np.asarray(d["timestamp"], dtype=float) / 1e6
        if spans is None:
            m = (ts >= self.t0) & (ts <= self.t1)
        else:
            m = np.zeros(len(ts), bool)
            for a, b in spans:
                m |= (ts >= a) & (ts <= b)
            m &= (ts >= self.t0) & (ts <= self.t1)
        return ts, m

    def rate(self, name, spans):
        """(rate_hz, kind, detail). kind is measured / capped / on-change / absent."""
        ts, m = self.mask(name, spans)
        if ts is None:
            return None, "absent", "not in this log"
        n = int(m.sum())
        if n < 2:
            return None, "absent", f"{n} samples in window"
        span = ts[m][-1] - ts[m][0]
        hz = (n - 1) / span if span > 0 else float("nan")

        # True inner/outer loop rates come from the module's own dt, not sample counts.
        true = self._true_rate(name)
        if true is not None:
            return true, "measured", "from mc_controller_status dt"

        # Only claim "on-change" for topics VERIFIED uncapped in logged_topics.cpp.
        # For anything else a low logged rate may be the logger, not the software -
        # guessing here would state a plausible falsehood, which is the failure mode
        # this whole tool is meant to avoid.
        if name in LOG_CAP_MS:
            cap = LOG_CAP_MS[name]
            if cap:
                return hz, "capped", f"logger cap {cap} ms = {1000.0 / cap:.0f} Hz max"
            return hz, "on-change", "uncapped in logged_topics.cpp"
        return hz, "logged", "cap UNKNOWN - grep logged_topics.cpp before trusting this"

    def _true_rate(self, name):
        st = self.topics.get("mc_controller_status")
        if st is None:
            return None
        field = {"vehicle_angular_velocity": "dt", "vehicle_torque_setpoint": "dt",
                 "vehicle_thrust_setpoint": "dt", "mc_controller_status": "dt",
                 "vehicle_attitude": "dt_attitude",
                 "vehicle_attitude_setpoint": "dt_position",
                 "vehicle_local_position": "dt_position",
                 "vehicle_local_position_setpoint": "dt_position"}.get(name)
        if field is None or field not in st:
            return None
        ts = np.asarray(st["timestamp"], dtype=float) / 1e6
        v = np.asarray(st[field], dtype=float)
        m = (ts >= self.t0) & (ts <= self.t1) & np.isfinite(v) & (v > 1e-6)
        if m.sum() < 10:
            return None
        return 1.0 / float(np.median(v[m]))

    def magnitude(self, name, spans):
        d = self.topics.get(name)
        if d is None:
            return ""
        ts, m = self.mask(name, spans)
        if m is None or m.sum() < 2:
            return ""
        picks = [f for f in ("xyz[0]", "xyz[1]", "xyz[2]", "roll", "pitch", "yaw",
                             "x", "y", "z", "control[0]") if f in d][:3]
        out = []
        for f in picks:
            v = np.asarray(d[f], dtype=float)[m]
            v = v[np.isfinite(v)]
            if len(v):
                out.append(f"{f}={np.sqrt(np.mean(v ** 2)):.4f}")
        return "RMS " + " ".join(out) if out else ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ulg")
    ap.add_argument("--values", action="store_true", help="add signal magnitudes")
    ap.add_argument("--mode", choices=list(LEVELS), help="restrict to one control level")
    a = ap.parse_args()

    L = Log(a.ulg)
    spans = L.restrict(a.mode)
    if a.mode and not spans:
        print(f"no {a.mode} segment in this log", file=sys.stderr)
        return 1

    fw = "mc_controller_status" in L.topics
    alg = L.u.initial_parameters.get("MC_CTRL_ALG", "?")
    dur = (sum(b - x for x, b in spans) if spans else L.t1 - L.t0)

    print("=" * 92)
    print(f"CONTROL CHAIN TRACE   {a.ulg.split('/')[-1]}")
    # The ACTIVE algorithm comes from the status topic, not initial_parameters.
    # MC_CTRL_ALG is reboot_required for 0 <-> non-zero, but the module also swaps
    # controllers live on a param change while disarmed - so the boot value can differ
    # from what actually flew, and reporting only the boot value misleads.
    active = ""
    if fw and "algorithm" in L.topics["mc_controller_status"]:
        seen = sorted(set(np.asarray(L.topics["mc_controller_status"]["algorithm"],
                                    dtype=float).astype(int)))
        names = {0: "stock", 1: "cascaded_pid", 2: "template"}
        active = "  active=" + ",".join(names.get(x, str(x)) for x in seen)
        if len(seen) > 1:
            active += "  <-- CHANGED MID-LOG"
    print(f"  build          : {'FRAMEWORK (mc_controller)' if fw else 'STOCK cascade'}"
          f"   MC_CTRL_ALG={alg} (at boot){active}")
    print(f"  window         : {'level ' + a.mode if a.mode else 'in-air'}, {dur:.1f} s")
    if fw:
        st = L.topics["mc_controller_status"]
        lv = np.asarray(st.get("control_level", [0]), dtype=float).astype(int)
        seen = sorted(set(lv))
        names = {0: "None", 1: "BodyRate", 2: "Attitude", 3: "Trajectory"}
        print(f"  levels flown   : {', '.join(names.get(x, str(x)) for x in seen)}")
        fb = np.asarray(st.get("fallback_active", [0]), dtype=float)
        print(f"  fallback       : {'ENGAGED' if fb.any() else 'never'}"
              f"    invalid outputs: {int(np.asarray(st.get('invalid_output_count', [0])).max())}")
    print("=" * 92)
    print("rate labels:  [measured] module's own dt   [capped] logger-limited, true rate is higher")
    print("              [on-change] event-driven     [absent] not published in this window")
    print("=" * 92)

    for idx, (label, trig, queue, ins, outs, note) in enumerate(CHAIN):
        last = idx == len(CHAIN) - 1
        print(f"\n{'└─' if last else '├─'} MODULE {label}")
        pad = "   " if last else "│  "
        print(f"{pad} queue    : {queue}")
        print(f"{pad} trigger  : {trig}")
        if note:
            print(f"{pad} note     : {note}")
        for tag, topics in (("IN ", ins), ("OUT", outs)):
            for t in topics:
                hz, kind, detail = L.rate(t, spans)
                shown = f"{hz:8.1f} Hz" if hz is not None else "        --"
                line = f"{pad}   {tag} {t:34s}{shown}  [{kind}]"
                if detail:
                    line += f"  {detail}"
                print(line)
                if a.values and tag == "OUT":
                    mag = L.magnitude(t, spans)
                    if mag:
                        print(f"{pad}       {'':38s}{mag}")

    print("\n" + "=" * 92)
    absent = [t for _, _, _, i, o, _ in CHAIN for t in i + o
              if L.rate(t, spans)[1] == "absent"]
    if absent:
        print("NOT PUBLISHED in this window (expected for a level that was not flown,")
        print("a topic the airframe does not produce, or a real publication defect):")
        for t in sorted(set(absent)):
            print(f"    {t}")
        print("\nCross-check a suspected defect with:  pub_matrix.py <stock.ulg> <this.ulg>")
    print("For true rates of [capped] topics, run on the live system: uorb top -1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
